### ISSUE TITLE
Text going out outside of screen

### ISSUE THREAD

**Issue by aravindvnair99** [yuvadm/cidr.xyz#89]
Viewing it on a S24 Ultra, I see that the text goes outside of the screen and when I fully zoom out, I see this:

![Screenshot_20240921_184349_Chrome](https://github.com/user-attachments/assets/5d8aaf65-08c0-49cc-b983-472ff429ac62)

**Comment by yuvadm** [comment]
What's your screen size?

We never had proper responsive screen support, I handled that in most components and now just have to figure out how to make the main input fields play nice on mobile.

At the very least I'll make a quick fix so that we don't have excessive horizontal scroll like you're seeing.

**Comment by yuvadm** [comment]
I also notice there's built in support for dark mode :joy: but that also requires some more styling work on my side.

**Comment by aravindvnair99** [comment]
> What's your screen size?

6.8 inch, 1440x3120 pixels. The screenshot is from a S24 Ultra.

> We never had proper responsive screen support

It was working fine with the previous version though.

> I also notice there's built in support for dark mode

Ah lol I just enabled a Chrome flag - chrome://flags/#darken-websites-checkbox-in-themes-setting

**Comment by aravindvnair99** [comment]
I just tried it in a few different mobile devices via Chrome Developer Tools and I see this behaviour in all of it.

**Comment by yuvadm** [comment]
Fixed in 32ff59a
